name: at-challenge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    environment:
      - NODE_ENV=development
  # app:
  #   image: mcr.microsoft.com/vscode/devcontainers/javascript-node:18
  #   volumes:
  #     - .:/workspace
  #   command: /bin/sh -c "while sleep 1000; do :; done"
  #   environment:
  #     - NODE_ENV=development
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "challenge"
    ports:
      - "1433:1433"
  # sqlserver:
  #   image: mcr.microsoft.com/azure-sql-edge
  #   environment:
  #     ACCEPT_EULA: Y
  #     MSSQL_USER: at
  #     MSSQL_SA_PASSWORD: challenge
  #   ports:
  #     - "1433:1433"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: at
      POSTGRES_PASSWORD: challenge
    ports:
      - "5432:5432"