name: at-challenge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ATChal1enge!"
    ports:
      - "1433:1433"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "ATChal1enge!"
    ports:
      - "5432:5432"